[project]
name = "my-strava-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
dependencies = [
    "python-dotenv>=1.1.1",
    "stravalib>=2.4",
    "tenacity>=9.1.2",
]
